"""update Verification.request_path type

Revision ID: 9f7cf6908a2f
Revises: 7c7afc9e071b
Create Date: 2022-09-04 13:08:36.633135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7cf6908a2f'
down_revision = '7c7afc9e071b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
